name : Install Oracle Java 8 on Ubuntu
desc : The recipe installs oracle jdk 8 on Ubuntu  
logo_url: https://raw.githubusercontent.com/tanmally/install-java-8/master/logo/Java8.png
tags:
    - java 8
    - oracle
    - latest
    - Ubunutu
 
task:

  - name: Install Oracle Java 8
    cmd:
        - export DEBIAN_FRONTEND=noninteractive
        - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
        - add-apt-repository -y ppa:webupd8team/java 
        - apt-get update
        - apt-get install -y oracle-java8-installer 
        - rm -rf /var/lib/apt/lists/*
        - rm -rf /var/cache/oracle-jdk8-installer        
        - apt-get clean
        # Set java env for all users
        - grep -q JAVA_HOME /etc/environment || echo 'JAVA_HOME="/usr/lib/jvm/java-8-oracle"' >> /etc/environment
