name : Install Java 8 on Ubunutu
desc : The recipe installs oracle jdk 8 on Ubunutu 16.04  
logo_url: https://raw.githubusercontent.com/tanmally/redis-install-fireworks/master/logo/redis.png
tags:
    - java 8
    - oracle
    - latest
    - Ubunutu
 
task:

  - name: Install Oracle Java 8
    cmd:
        - export DEBIAN_FRONTEND=noninteractive
        - apt-get -y update
        - apt-get -y upgrade
        - apt-get -y software-properties-common   
        - add-apt-repository ppa:webupd8team/java -y  
        - apt-get -y update
        - echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections         
        - apt-get install -y oracle-java8-installer
        - apt-get clean
        # Set java env for all users
        - grep -q JAVA_HOME /etc/environment || echo 'JAVA_HOME="/usr/lib/jvm/java-8-oracle"' >> /etc/environment

    